spring.application.name=skincare-backend

spring.datasource.url=${CONNECTION_STRING_POSTGRESQL}
spring.datasource.username=${POSTGRESQL_USERNAME}
spring.datasource.password=${POSTGRESQL_PASSWORD}

# Spring Boot-loggan inte visas i konsolen vid start
spring.main.banner-mode=off
logging.level.org.springframework=ERROR

logging.level.org.springframework.boot.autoconfigure.security=INFO
logging.file.name=app.log
logging.level.com.parmida98.school_webpage=INFO

# Säger till Hibernate att automatiskt uppdatera databasschemat efter Entities
spring.jpa.hibernate.ddl-auto=update

# Import .env file
spring.config.import=optional:file:.env[.properties]

# vill att DB styrs via migrationer,
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

